version: "3.9"
services:

    efb:
        container_name: efb
        image: xzsk2/efb-docker:latest
        restart: unless-stopped
        volumes:
            - ./efb:/app/config
        network_mode: "host"
        command:
            - /bin/sh
            - -c
            - |
                echo "sleep for 20sec"
                sleep 20
                ehforwarderbot
